sudo: false

notifications:
  email: false

language: python
cache: pip

services:
  - elasticsearch

addons:
  apt:
    packages:
    - yui-compressor

install:
  - pip install -U pip
  - bundle install --deployment --path ../gems --binstubs ../gem-bin
  # Now install the rest of the required Python packages:
  - CFLAGS="-O0" pip install -r requirements.txt
  - pip install python-coveralls
  - pip install scrutinizer-ocular
  - pip check
  # Create a basic general.yml file:
  - sed -r
    -e "s,(POMBOLA_DB_USER:) 'sayit',\\1 'postgres',"
    -e "s,(POMBOLA_DB_NAME:) '',\\1 'pombola',"
    -e "s,(DJANGO_SECRET_KEY:) '',\\1 'notatallsecret',"
    conf/general.yml-example > conf/general.yml

before_script:
  - createdb -U postgres pombola
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d pombola
  - ./manage.py migrate --noinput
  - ./manage.py collectstatic --noinput

script:
  - ./run-tests --coverage

after_success:
  - coveralls
  - ocular --data-file ".coverage"
