sudo: false

notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#build"
    use_notice: true
    skip_join: true

language: python

services:
  - elasticsearch

addons:
  apt:
    packages:
    - yui-compressor

install:
  - gem install --no-ri --no-rdoc compass -v 0.12.7
  # Now install the rest of the required Python packages:
  - CFLAGS="-O0" pip install -r requirements.txt --use-mirrors
  # Create a basic general.yml file:
  - sed -r
    -e "s,(POMBOLA_DB_USER:) 'sayit',\\1 'postgres',"
    -e "s,(POMBOLA_DB_NAME:) '',\\1 'pombola',"
    -e "s,(DJANGO_SECRET_KEY:) '',\\1 'notatallsecret',"
    conf/general.yml-example > conf/general.yml

before_script:
  - createdb -U postgres pombola
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d pombola
  - ./manage.py migrate --noinput
  - ./manage.py collectstatic --noinput

script:
  - ./run-tests
